// <auto-generated />
using Legitarsasag_Roli.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Legitarsasag_Roli.Migrations
{
    [DbContext(typeof(LegitarsasagContext))]
    partial class LegitarsasagContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Legitarsasag_Roli.Entities.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wizz Air"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wizz Air"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wizz Air"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wizz Air"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Wizz Air"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Wizz Air"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Wizz Air"
                        },
                        new
                        {
                            Id = 8,
                            Name = "British Airways"
                        },
                        new
                        {
                            Id = 9,
                            Name = "British Airways"
                        },
                        new
                        {
                            Id = 10,
                            Name = "British Airways"
                        },
                        new
                        {
                            Id = 11,
                            Name = "British Airways"
                        },
                        new
                        {
                            Id = 12,
                            Name = "British Airways"
                        },
                        new
                        {
                            Id = 13,
                            Name = "British Airways"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Lufthansa"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Lufthansa"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Lufthansa"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Lufthansa"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Lufthansa"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Lufthansa"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Lufthansa"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Lufthansa"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Lufthansa"
                        });
                });

            modelBuilder.Entity("Legitarsasag_Roli.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Budapest",
                            Population = 1800000
                        },
                        new
                        {
                            Id = 2,
                            Name = "London",
                            Population = 8800000
                        },
                        new
                        {
                            Id = 3,
                            Name = "Los Angeles",
                            Population = 13800000
                        },
                        new
                        {
                            Id = 4,
                            Name = "Madrid",
                            Population = 3100000
                        },
                        new
                        {
                            Id = 5,
                            Name = "New York",
                            Population = 8500000
                        },
                        new
                        {
                            Id = 6,
                            Name = "Roma",
                            Population = 2900000
                        },
                        new
                        {
                            Id = 7,
                            Name = "Washington",
                            Population = 2700000
                        });
                });

            modelBuilder.Entity("Legitarsasag_Roli.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Airline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CityFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Distance")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Airline = "Wizz Air",
                            CityFrom = "Budapest",
                            CityTo = "London",
                            Distance = 1450,
                            Duration = 145
                        },
                        new
                        {
                            Id = 2,
                            Airline = "Wizz Air",
                            CityFrom = "Budapest",
                            CityTo = "Roma",
                            Distance = 810,
                            Duration = 105
                        },
                        new
                        {
                            Id = 3,
                            Airline = "Wizz Air",
                            CityFrom = "Budapest",
                            CityTo = "Madrid",
                            Distance = 1975,
                            Duration = 195
                        },
                        new
                        {
                            Id = 4,
                            Airline = "Wizz Air",
                            CityFrom = "Roma",
                            CityTo = "London",
                            Distance = 1435,
                            Duration = 210
                        },
                        new
                        {
                            Id = 5,
                            Airline = "Wizz Air",
                            CityFrom = "Roma",
                            CityTo = "Madrid",
                            Distance = 1365,
                            Duration = 205
                        },
                        new
                        {
                            Id = 6,
                            Airline = "Wizz Air",
                            CityFrom = "London",
                            CityTo = "Madrid",
                            Distance = 1265,
                            Duration = 190
                        },
                        new
                        {
                            Id = 7,
                            Airline = "Wizz Air",
                            CityFrom = "Madrid",
                            CityTo = "London",
                            Distance = 1265,
                            Duration = 190
                        },
                        new
                        {
                            Id = 8,
                            Airline = "British Airways",
                            CityFrom = "Budapest",
                            CityTo = "London",
                            Distance = 1450,
                            Duration = 155
                        },
                        new
                        {
                            Id = 9,
                            Airline = "British Airways",
                            CityFrom = "Budapest",
                            CityTo = "Madrid",
                            Distance = 1975,
                            Duration = 205
                        },
                        new
                        {
                            Id = 10,
                            Airline = "British Airways",
                            CityFrom = "London",
                            CityTo = "New York",
                            Distance = 5510,
                            Duration = 470
                        },
                        new
                        {
                            Id = 11,
                            Airline = "British Airways",
                            CityFrom = "New York",
                            CityTo = "Washington",
                            Distance = 475,
                            Duration = 55
                        },
                        new
                        {
                            Id = 12,
                            Airline = "British Airways",
                            CityFrom = "Washington",
                            CityTo = "New York",
                            Distance = 475,
                            Duration = 55
                        },
                        new
                        {
                            Id = 13,
                            Airline = "British Airways",
                            CityFrom = "Washington",
                            CityTo = "Los Angeles",
                            Distance = 3695,
                            Duration = 340
                        },
                        new
                        {
                            Id = 14,
                            Airline = "Lufthansa",
                            CityFrom = "Budapest",
                            CityTo = "London",
                            Distance = 1450,
                            Duration = 150
                        },
                        new
                        {
                            Id = 15,
                            Airline = "Lufthansa",
                            CityFrom = "Budapest",
                            CityTo = "Madrid",
                            Distance = 1975,
                            Duration = 210
                        },
                        new
                        {
                            Id = 16,
                            Airline = "Lufthansa",
                            CityFrom = "London",
                            CityTo = "New York",
                            Distance = 5510,
                            Duration = 485
                        },
                        new
                        {
                            Id = 17,
                            Airline = "Lufthansa",
                            CityFrom = "London",
                            CityTo = "Washington",
                            Distance = 5900,
                            Duration = 480
                        },
                        new
                        {
                            Id = 18,
                            Airline = "Lufthansa",
                            CityFrom = "Madrid",
                            CityTo = "Washington",
                            Distance = 6090,
                            Duration = 470
                        },
                        new
                        {
                            Id = 19,
                            Airline = "Lufthansa",
                            CityFrom = "New York",
                            CityTo = "Washington",
                            Distance = 475,
                            Duration = 55
                        },
                        new
                        {
                            Id = 20,
                            Airline = "Lufthansa",
                            CityFrom = "Washington",
                            CityTo = "New York",
                            Distance = 475,
                            Duration = 55
                        },
                        new
                        {
                            Id = 21,
                            Airline = "Lufthansa",
                            CityFrom = "New York",
                            CityTo = "Los Angeles",
                            Distance = 3805,
                            Duration = 350
                        },
                        new
                        {
                            Id = 22,
                            Airline = "Lufthansa",
                            CityFrom = "Washington",
                            CityTo = "Los Angeles",
                            Distance = 3695,
                            Duration = 340
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
